package com.academicquest.enums;

public enum TIPO_NOTIFICACAO {

    NOTIFICACAO_NOVO_PROJETO,
    NOTIFICACAO_NOVA_ATIVIDADE,
    NOTIFICACAO_ATIVIDADE_GRUPO_CORRIGIDA,
    NOTIFICACAO_MENSAGEM;

}
